#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("node_in_strm_V_dout", 32, hls_in, 0, "ap_fifo", "fifo_data", 1433),
	Port_Property("node_in_strm_V_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1433),
	Port_Property("node_in_strm_V_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 1433),
	Port_Property("edge_strm_V_src_V_dout", 12, hls_in, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("edge_strm_V_src_V_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("edge_strm_V_src_V_read", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("edge_strm_V_dst_V_dout", 12, hls_in, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("edge_strm_V_dst_V_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("edge_strm_V_dst_V_read", 1, hls_out, 2, "ap_fifo", "fifo_update", 1),
	Port_Property("edge_strm_V_c_dout", 32, hls_in, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("edge_strm_V_c_empty_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("edge_strm_V_c_read", 1, hls_out, 3, "ap_fifo", "fifo_update", 1),
	Port_Property("metadata_strm_V_dout", 64, hls_in, 4, "ap_fifo", "fifo_data", 85),
	Port_Property("metadata_strm_V_empty_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 85),
	Port_Property("metadata_strm_V_read", 1, hls_out, 4, "ap_fifo", "fifo_update", 85),
	Port_Property("node_out_strm_V_din", 32, hls_out, 5, "ap_fifo", "fifo_data", 16),
	Port_Property("node_out_strm_V_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 16),
	Port_Property("node_out_strm_V_write", 1, hls_out, 5, "ap_fifo", "fifo_update", 16),
	Port_Property("wt_address0", 15, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("wt_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("wt_q0", 32, hls_in, 6, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "top";
