lappend pragmaStatus0 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "node_in_strm"}
lappend pragmaStatus1 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "edge_strm"}
lappend pragmaStatus2 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "metadata_strm"}
lappend pragmaStatus3 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Variable 'msg_out_strm' is not declared in 'top'." variable "msg_out_strm"}
lappend pragmaStatus4 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Variable 'msg_in_strm' is not declared in 'top'." variable "msg_in_strm"}
lappend pragmaStatus5 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "node_out_strm"}
lappend pragmaStatus6 {pragma "RESOURCE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "wt"}
lappend pragmaStatus7 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "node_load" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'node_load' does not exist in any synthesis source file." variable "node_in_strm"}
lappend pragmaStatus9 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "edge_proc" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'edge_proc' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "edge_proc" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'edge_proc' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "mat_mult" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'mat_mult' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "mat_mult" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'mat_mult' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "edge_list"}
lappend pragmaStatus14 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "node_in_list"}
lappend pragmaStatus15 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "node_out_list"}
lappend pragmaStatus16 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "msg_in_list"}
lappend pragmaStatus17 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "msg_out_list"}
lappend pragmaStatus18 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "metadata_strm"}
lappend pragmaStatus19 {pragma "PIPELINE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top/clear_inner" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'clear_inner' does not exist in function 'top'. "}
lappend pragmaStatus20 {pragma "PIPELINE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "node_store/node_store_inner" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'node_store' does not exist in any synthesis source file."}
lappend pragmaStatus21 {pragma "PIPELINE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "node_load/src_load_inner" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'node_load' does not exist in any synthesis source file."}
lappend pragmaStatus22 {pragma "DATAFLOW" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top/scatter_outer" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Label 'scatter_outer' does not exist in function 'top'. "}
lappend pragmaStatus23 {pragma "DATAFLOW" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/top.cpp" location "top/gather_outer" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Label 'gather_outer' does not exist in function 'top'. "}
lappend pragmaStatus0 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "node_in_strm"}
lappend pragmaStatus1 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "edge_strm"}
lappend pragmaStatus2 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "metadata_strm"}
lappend pragmaStatus3 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "msg_out_strm"}
lappend pragmaStatus4 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "msg_in_strm"}
lappend pragmaStatus5 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "node_out_strm"}
lappend pragmaStatus6 {pragma "RESOURCE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P' cannot be applied: Function 'top' does not exist in any synthesis source file." variable "wt"}
lappend pragmaStatus7 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'top' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "node_load" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'node_load' does not exist in any synthesis source file." variable "node_in_strm"}
lappend pragmaStatus9 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "edge_proc" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'edge_proc' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "edge_proc" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'edge_proc' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "mat_mult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "INTERFACE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "mat_mult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "edge_list"}
lappend pragmaStatus14 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "node_in_list"}
lappend pragmaStatus15 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "node_out_list"}
lappend pragmaStatus16 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "msg_in_list"}
lappend pragmaStatus17 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "msg_out_list"}
lappend pragmaStatus18 {pragma "STREAM" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "metadata_strm"}
lappend pragmaStatus19 {pragma "PIPELINE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top/clear_inner" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'top' does not exist in any synthesis source file."}
lappend pragmaStatus20 {pragma "PIPELINE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "node_store/node_store_inner" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'node_store' does not exist in any synthesis source file."}
lappend pragmaStatus21 {pragma "PIPELINE" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "node_load/src_load_inner" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'node_load' does not exist in any synthesis source file."}
lappend pragmaStatus22 {pragma "DATAFLOW" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top/scatter_outer" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'top' does not exist in any synthesis source file."}
lappend pragmaStatus23 {pragma "DATAFLOW" source "/home/yuzou/gcn_fpga_exp1/gcn_fpga_hls/src/mat_mult.cpp" location "top/gather_outer" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'top' does not exist in any synthesis source file."}
