# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/PCIeGen2x8If128/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/PCIeGen2x8If128/source/PCIeGen2x8If128-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: ip/PCIeGen2x8If128/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: ip/PCIeGen2x8If128/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/PCIeGen2x8If128/source/PCIeGen2x8If128-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: ip/PCIeGen2x8If128/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
