// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _top_HH_
#define _top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "top_fadd_32ns_32nbkb.h"
#include "top_node_in_bram.h"
#include "top_node_out_bram.h"

namespace ap_rtl {

struct top : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > node_in_strm_V_dout;
    sc_in< sc_logic > node_in_strm_V_empty_n;
    sc_out< sc_logic > node_in_strm_V_read;
    sc_in< sc_lv<12> > edge_strm_V_src_V_dout;
    sc_in< sc_logic > edge_strm_V_src_V_empty_n;
    sc_out< sc_logic > edge_strm_V_src_V_read;
    sc_in< sc_lv<12> > edge_strm_V_dst_V_dout;
    sc_in< sc_logic > edge_strm_V_dst_V_empty_n;
    sc_out< sc_logic > edge_strm_V_dst_V_read;
    sc_in< sc_lv<32> > edge_strm_V_c_dout;
    sc_in< sc_logic > edge_strm_V_c_empty_n;
    sc_out< sc_logic > edge_strm_V_c_read;
    sc_in< sc_lv<64> > metadata_strm_V_dout;
    sc_in< sc_logic > metadata_strm_V_empty_n;
    sc_out< sc_logic > metadata_strm_V_read;
    sc_out< sc_lv<32> > node_out_strm_V_din;
    sc_in< sc_logic > node_out_strm_V_full_n;
    sc_out< sc_logic > node_out_strm_V_write;
    sc_out< sc_lv<15> > wt_address0;
    sc_out< sc_logic > wt_ce0;
    sc_in< sc_lv<32> > wt_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    top(sc_module_name name);
    SC_HAS_PROCESS(top);

    ~top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    top_node_in_bram* node_in_bram_U;
    top_node_out_bram* node_out_bram_U;
    top_fadd_32ns_32nbkb<1,8,32,32,32>* top_fadd_32ns_32nbkb_U1;
    sc_signal< sc_lv<21> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_logic > node_in_strm_V_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > exitcond5_fu_469_p2;
    sc_signal< sc_logic > edge_strm_V_src_V_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > exitcond6_fu_506_p2;
    sc_signal< sc_logic > edge_strm_V_dst_V_blk_n;
    sc_signal< sc_logic > edge_strm_V_c_blk_n;
    sc_signal< sc_logic > metadata_strm_V_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_logic > node_out_strm_V_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state21;
    sc_signal< sc_lv<7> > dst_1_fu_396_p2;
    sc_signal< sc_lv<7> > dst_1_reg_599;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > indvarinc_fu_402_p2;
    sc_signal< sc_lv<5> > indvarinc_reg_604;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > indvarinc1_fu_408_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<7> > src_1_fu_445_p2;
    sc_signal< sc_lv<7> > src_1_reg_623;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<16> > next_mul_fu_451_p2;
    sc_signal< sc_lv<16> > next_mul_reg_628;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<6> > row_2_fu_463_p2;
    sc_signal< sc_lv<6> > row_2_reg_636;
    sc_signal< sc_lv<11> > col_2_fu_475_p2;
    sc_signal< sc_lv<32> > node_in_bram_q0;
    sc_signal< sc_lv<32> > node_in_bram_load_reg_649;
    sc_signal< sc_lv<32> > tmp_s_reg_654;
    sc_signal< sc_lv<32> > i_1_fu_511_p2;
    sc_signal< sc_lv<32> > i_1_reg_662;
    sc_signal< sc_logic > edge_strm_V_c0_status;
    sc_signal< sc_lv<32> > tmp_c_reg_667;
    sc_signal< sc_lv<5> > tmp_9_fu_525_p1;
    sc_signal< sc_lv<5> > tmp_9_reg_672;
    sc_signal< sc_lv<32> > grp_fu_386_p2;
    sc_signal< sc_lv<32> > tmp_8_reg_677;
    sc_signal< sc_lv<1> > ap_CS_fsm_state17;
    sc_signal< sc_lv<6> > row_1_fu_547_p2;
    sc_signal< sc_lv<6> > row_1_reg_685;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<11> > tmp_9_cast_fu_561_p1;
    sc_signal< sc_lv<11> > tmp_9_cast_reg_690;
    sc_signal< sc_lv<1> > exitcond3_fu_541_p2;
    sc_signal< sc_lv<5> > col_1_fu_571_p2;
    sc_signal< sc_lv<5> > col_1_reg_698;
    sc_signal< sc_lv<1> > ap_CS_fsm_state20;
    sc_signal< sc_lv<1> > exitcond_fu_565_p2;
    sc_signal< sc_lv<16> > node_in_bram_address0;
    sc_signal< sc_logic > node_in_bram_ce0;
    sc_signal< sc_logic > node_in_bram_we0;
    sc_signal< sc_lv<9> > node_out_bram_address0;
    sc_signal< sc_logic > node_out_bram_ce0;
    sc_signal< sc_logic > node_out_bram_we0;
    sc_signal< sc_lv<32> > node_out_bram_d0;
    sc_signal< sc_lv<32> > node_out_bram_q0;
    sc_signal< sc_lv<7> > dst_reg_274;
    sc_signal< sc_lv<5> > invdar_reg_285;
    sc_signal< sc_lv<1> > tmp_3_fu_433_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_427_p2;
    sc_signal< sc_lv<1> > exitcond1_fu_390_p2;
    sc_signal< sc_lv<4> > invdar1_reg_297;
    sc_signal< sc_lv<7> > src_reg_308;
    sc_signal< sc_lv<6> > row_reg_319;
    sc_signal< sc_lv<1> > exitcond2_fu_439_p2;
    sc_signal< sc_lv<16> > phi_mul_reg_330;
    sc_signal< sc_lv<11> > col_reg_342;
    sc_signal< sc_lv<1> > exitcond4_fu_457_p2;
    sc_signal< sc_lv<32> > i_reg_353;
    sc_signal< sc_lv<1> > ap_CS_fsm_state18;
    sc_signal< sc_lv<6> > row1_reg_364;
    sc_signal< sc_lv<5> > col2_reg_375;
    sc_signal< sc_lv<64> > tmp_1_fu_422_p1;
    sc_signal< sc_lv<64> > tmp_20_cast_fu_491_p1;
    sc_signal< sc_lv<64> > tmp_11_fu_536_p1;
    sc_signal< sc_lv<64> > tmp_15_cast_fu_586_p1;
    sc_signal< sc_logic > edge_strm_V_c0_update;
    sc_signal< sc_lv<1> > ap_CS_fsm_state10;
    sc_signal< sc_lv<9> > tmp_fu_414_p3;
    sc_signal< sc_lv<16> > tmp_10_cast_fu_481_p1;
    sc_signal< sc_lv<16> > tmp_13_fu_485_p2;
    sc_signal< sc_lv<9> > tmp_10_fu_529_p3;
    sc_signal< sc_lv<10> > tmp_5_fu_553_p3;
    sc_signal< sc_lv<11> > tmp_cast_fu_577_p1;
    sc_signal< sc_lv<11> > tmp_6_fu_581_p2;
    sc_signal< sc_lv<21> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<21> ap_ST_fsm_state1;
    static const sc_lv<21> ap_ST_fsm_state2;
    static const sc_lv<21> ap_ST_fsm_state3;
    static const sc_lv<21> ap_ST_fsm_state4;
    static const sc_lv<21> ap_ST_fsm_state5;
    static const sc_lv<21> ap_ST_fsm_state6;
    static const sc_lv<21> ap_ST_fsm_state7;
    static const sc_lv<21> ap_ST_fsm_state8;
    static const sc_lv<21> ap_ST_fsm_state9;
    static const sc_lv<21> ap_ST_fsm_state10;
    static const sc_lv<21> ap_ST_fsm_state11;
    static const sc_lv<21> ap_ST_fsm_state12;
    static const sc_lv<21> ap_ST_fsm_state13;
    static const sc_lv<21> ap_ST_fsm_state14;
    static const sc_lv<21> ap_ST_fsm_state15;
    static const sc_lv<21> ap_ST_fsm_state16;
    static const sc_lv<21> ap_ST_fsm_state17;
    static const sc_lv<21> ap_ST_fsm_state18;
    static const sc_lv<21> ap_ST_fsm_state19;
    static const sc_lv<21> ap_ST_fsm_state20;
    static const sc_lv<21> ap_ST_fsm_state21;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<7> ap_const_lv7_55;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<16> ap_const_lv16_599;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<11> ap_const_lv11_599;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<15> ap_const_lv15_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_clk_pos_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_col_1_fu_571_p2();
    void thread_col_2_fu_475_p2();
    void thread_dst_1_fu_396_p2();
    void thread_edge_strm_V_c0_status();
    void thread_edge_strm_V_c0_update();
    void thread_edge_strm_V_c_blk_n();
    void thread_edge_strm_V_c_read();
    void thread_edge_strm_V_dst_V_blk_n();
    void thread_edge_strm_V_dst_V_read();
    void thread_edge_strm_V_src_V_blk_n();
    void thread_edge_strm_V_src_V_read();
    void thread_exitcond1_fu_390_p2();
    void thread_exitcond2_fu_439_p2();
    void thread_exitcond3_fu_541_p2();
    void thread_exitcond4_fu_457_p2();
    void thread_exitcond5_fu_469_p2();
    void thread_exitcond6_fu_506_p2();
    void thread_exitcond_fu_565_p2();
    void thread_i_1_fu_511_p2();
    void thread_indvarinc1_fu_408_p2();
    void thread_indvarinc_fu_402_p2();
    void thread_metadata_strm_V_blk_n();
    void thread_metadata_strm_V_read();
    void thread_next_mul_fu_451_p2();
    void thread_node_in_bram_address0();
    void thread_node_in_bram_ce0();
    void thread_node_in_bram_we0();
    void thread_node_in_strm_V_blk_n();
    void thread_node_in_strm_V_read();
    void thread_node_out_bram_address0();
    void thread_node_out_bram_ce0();
    void thread_node_out_bram_d0();
    void thread_node_out_bram_we0();
    void thread_node_out_strm_V_blk_n();
    void thread_node_out_strm_V_din();
    void thread_node_out_strm_V_write();
    void thread_row_1_fu_547_p2();
    void thread_row_2_fu_463_p2();
    void thread_src_1_fu_445_p2();
    void thread_tmp_10_cast_fu_481_p1();
    void thread_tmp_10_fu_529_p3();
    void thread_tmp_11_fu_536_p1();
    void thread_tmp_13_fu_485_p2();
    void thread_tmp_15_cast_fu_586_p1();
    void thread_tmp_1_fu_422_p1();
    void thread_tmp_20_cast_fu_491_p1();
    void thread_tmp_2_fu_427_p2();
    void thread_tmp_3_fu_433_p2();
    void thread_tmp_5_fu_553_p3();
    void thread_tmp_6_fu_581_p2();
    void thread_tmp_9_cast_fu_561_p1();
    void thread_tmp_9_fu_525_p1();
    void thread_tmp_cast_fu_577_p1();
    void thread_tmp_fu_414_p3();
    void thread_wt_address0();
    void thread_wt_ce0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
