# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/KC705_Gen2x8If128.xdc

# IP: ip/node_out_strm/node_out_strm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==node_out_strm || ORIG_REF_NAME==node_out_strm}]

# IP: ip/metadata_strm/metadata_strm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metadata_strm || ORIG_REF_NAME==metadata_strm}]
