# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yuzou/gcn_fpga_exp1/gcn_fpga_hw/gcn_fpga_hw.srcs/sources_1/ip/dst_stream/dst_stream.xci
# IP: The module: 'dst_stream' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/gcn_fpga_exp1/gcn_fpga_hw/gcn_fpga_hw.srcs/sources_1/ip/dst_stream/dst_stream/dst_stream.xdc
# XDC: The top module name and the constraint reference have the same name: 'dst_stream'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/yuzou/gcn_fpga_exp1/gcn_fpga_hw/gcn_fpga_hw.srcs/sources_1/ip/dst_stream/dst_stream_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dst_stream'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/yuzou/gcn_fpga_exp1/gcn_fpga_hw/gcn_fpga_hw.srcs/sources_1/ip/dst_stream/dst_stream.xci
# IP: The module: 'dst_stream' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/gcn_fpga_exp1/gcn_fpga_hw/gcn_fpga_hw.srcs/sources_1/ip/dst_stream/dst_stream/dst_stream.xdc
# XDC: The top module name and the constraint reference have the same name: 'dst_stream'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/yuzou/gcn_fpga_exp1/gcn_fpga_hw/gcn_fpga_hw.srcs/sources_1/ip/dst_stream/dst_stream_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dst_stream'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
